-- Could not auto-generate a down migration.
-- Please write an appropriate down migration for the SQL below:
-- alter table "public"."collections" add column "error_fetching" boolean
--  not null default 'false';
