version: 3
# endpoint: https://apemonitor-staging.herokuapp.com/
endpoint: https://prod-apemonitor.herokuapp.com/
# admin_secret: vvf84Zj42XCq2I
admin_secret: P@3SvzaJgW8t
metadata_directory: metadata
actions:
  kind: synchronous
  handler_webhook_baseurl: http://localhost:3000
