-- Could not auto-generate a down migration.
-- Please write an appropriate down migration for the SQL below:
-- alter table "public"."collections" add column "is_stats_fetched" boolean
--  not null default 'false';
